version: '3.7'
services:
  mosquitto:
    image: eclipse-mosquitto:${MOSQUITTO_IMAGE_VERSION}
    init: true
    restart: always
    ports:
      - ${MOSQUITTO_MQQT_PORT}:1883
      - ${MOSQUITTO_WS_PORT}:9001
    volumes:
      - ${VOLUMES_DIR}/mosquitto/conf:/mosquitto/config
      - ${VOLUMES_DIR}/mosquitto/data:/mosquitto/data
      - ${VOLUMES_DIR}/mosquitto/log:/mosquitto/log
    networks:
      - default
  influxdb:
    image: influxdb:${INFLUXDB_IMAGE_VERSION}
    init: true
    restart: always
    ports:
      - ${INFLUXDB_HTTP_PORT}:8086
      #- ${INFLUXDB_RPC_PORT}:8088
    volumes:
      - ${VOLUMES_DIR}/influxdb/data:/var/lib/influxdb
      - ${VOLUMES_DIR}/influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    networks:
      - influxdb
  grafana:
    image: grafana/grafana:${GRAFANA_IMAGE_VERSION}
    init: true
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    #volumes:
      #- ${VOLUMES_DIR}/grafana/data:/var/lib/grafana
      #- ${VOLUMES_DIR}/grafana/log:/var/log/grafana
    networks:
      - default
      - influxdb
    depends_on: 
      - influxdb
  kotori:
    image: daqzilla/kotori:${KOTORI_IMAGE_VERSION}
    restart: always
    ports:
      - ${KOTORI_PORT}:24642
    command: "kotori --config /etc/kotori/production.ini"
    volumes:
      - ${VOLUMES_DIR}/kotori/conf:/etc/kotori
    networks:
      - default
      - influxdb
    depends_on:
      - mosquitto
      - influxdb
      - grafana
networks:
  influxdb:
